name: t7_gis_professional
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11
  
  # Essential GIS Libraries
  - geopandas=1.1
  - rasterio=1.3
  - shapely=2.0
  - fiona=1.9
  - pyproj=3.6
  - gdal=3.8
  
  # Performance and Large Data Handling
  - dask
  - dask-geopandas
  - xarray
  - rioxarray
  - h5py
  - netcdf4
  
  # QGIS Integration
  - qgis=3.34
  
  # Scientific Computing
  - numpy=1.24
  - pandas=2.0
  - scipy
  - scikit-learn
  
  # Visualization
  - matplotlib
  - seaborn
  - plotly
  - folium
  - contextily
  - hvplot
  - panel
  - bokeh
  
  # Development Tools
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  
  # Code Quality
  - black
  - flake8
  - pytest
  - mypy
  
  # Database Connectivity
  - psycopg2
  - sqlite
  - sqlalchemy
  
  # File Formats
  - openpyxl
  - xlsxwriter
  - h5netcdf
  
  # Utility Libraries
  - requests
  - pyyaml
  - tqdm
  - click
  
  # Pip-only packages
  - pip
  - pip:
    - geocoder
    - geopy  
    - rasterstats
    - earthpy
    - pysal
    - momepy
    - osmnx